name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: API

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: toolshop_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, tokenizer, bcmath
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Show .env
        run: cat .env

      - name: Generate application key
        run: php artisan key:generate
      
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run migrations
        run: php artisan migrate --force

      # - name: Run API tests
        # run: vendor/bin/phpunit --testsuite Feature
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Register API tests
        run: newman run tests/register_collection.json --folder "register" --iteration-data tests/register_data.csv

      - name: Run Login API tests
        run: newman run tests/login_collection.json --folder "login" --iteration-data tests/login_data.csv

      - name: Run Forgot Password API tests
        run: newman run tests/forgot_password_collection.json --folder "forgot password" --iteration-data tests/forgot_password_data.csv