name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set SPRINT env
        run: echo "SPRINT=sprint5-with-bugs" >> $GITHUB_ENV
      - name: Copy .env
        run: cp ${SPRINT}/API/.env.example ${SPRINT}/API/.env
      - name: Update .env for CI
        run: |
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=toolshop/' ${SPRINT}/API/.env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=user/' ${SPRINT}/API/.env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' ${SPRINT}/API/.env
          sed -i 's/DB_HOST=.*/DB_HOST=mariadb/' ${SPRINT}/API/.env

      - name: Start containers
        run: |
          docker compose up -d --build

      - name: Wait for web service (API)
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8091/; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done
      - name: Install Composer dependencies
        run: docker compose run --rm composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: Fix storage permissions
        run: docker compose exec -T laravel-api chmod -R 777 storage bootstrap/cache

      - name: Run migrations and seed
        run: docker compose exec -T -e APP_ENV=local laravel-api php artisan migrate:fresh --seed

      # - name: Run API tests
        # run: vendor/bin/phpunit --testsuite Feature
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Register API tests
        run: newman run API/tests/register_collection.json --iteration-data tests/register_data.csv --environment API/tests/api_environment.json

      - name: Run Login API tests
        run: newman run API/tests/login_collection.json --iteration-data tests/login_data.csv --environment API/tests/api_environment.json

      - name: Run Forgot Password API tests
        run: newman run API/tests/forgot_password_collection.json --iteration-data tests/forgot_password_data.csv --environment API/tests/api_environment.json

      - name: Stop containers
        if: always()
        run: docker compose down -v